name: ssmsapp1
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:

  flutter:
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.3
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  cloud_firestore: ^4.8.1
  csv: ^5.0.2
  file_picker: ^4.3.3
  http: ^1.1.0

  shimmer: ^3.0.0
  flutter_spinkit: any
  syncfusion_flutter_barcodes: ^24.1.47


  hive: ^2.0.4
  hive_flutter: ^1.1.0
  lottie: ^2.7.0





  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  google_sign_in: ^6.1.3
  table_calendar: ^3.0.9
  flutter_staggered_grid_view: ^0.6.2
  qr_flutter: ^4.1.0

  image_picker: ^0.8.4+4
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  local_auth: ^2.1.7





  uuid: ^3.0.5
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
