// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNd-IR37pZJ9ZIxI_WH-_mpD0JTnDfgY',
    appId: '1:779980475967:web:0f35dcdfe74d86bf78728a',
    messagingSenderId: '779980475967',
    projectId: 'ssmsapp1',
    authDomain: 'ssmsapp1.firebaseapp.com',
    storageBucket: 'ssmsapp1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiFPOyfSJ2FNfd-ACRRhEbY7OLrINKT7Q',
    appId: '1:779980475967:android:3ba7ed4622fa1fd578728a',
    messagingSenderId: '779980475967',
    projectId: 'ssmsapp1',
    storageBucket: 'ssmsapp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADCWVZHCtXjiOigFfTamloeAL9pbhgc6c',
    appId: '1:779980475967:ios:1e97301471c9792078728a',
    messagingSenderId: '779980475967',
    projectId: 'ssmsapp1',
    storageBucket: 'ssmsapp1.appspot.com',
    iosClientId: '779980475967-76fkmi6scdcmq5aejvr8040psfjjm5qn.apps.googleusercontent.com',
    iosBundleId: 'gupta.aryan.com.ssmsapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADCWVZHCtXjiOigFfTamloeAL9pbhgc6c',
    appId: '1:779980475967:ios:1e97301471c9792078728a',
    messagingSenderId: '779980475967',
    projectId: 'ssmsapp1',
    storageBucket: 'ssmsapp1.appspot.com',
    iosClientId: '779980475967-76fkmi6scdcmq5aejvr8040psfjjm5qn.apps.googleusercontent.com',
    iosBundleId: 'gupta.aryan.com.ssmsapp1',
  );
}
